const { DataTypes } = require("sequelize")
const sequelize = require("../config/database")

const Funcionario = sequelize.define("Funcionario", {
  clienteId: { type: DataTypes.INTEGER, allowNull: false },
  cliente: { type: DataTypes.STRING, allowNull: false },
  matricula: { type: DataTypes.STRING, allowNull: true },
  nome: { type: DataTypes.STRING, allowNull: false },
  nomeSocial: { type: DataTypes.STRING, allowNull: true },
  cpf: { type: DataTypes.STRING, allowNull: false },
  rg: { type: DataTypes.STRING, allowNull: true },
  orgaoEmissorRg: { type: DataTypes.STRING, allowNull: true },
  dataEmissaoRg: { type: DataTypes.DATEONLY, allowNull: true },
  dataNascimento: { type: DataTypes.DATEONLY, allowNull: false },
  sexo: { type: DataTypes.STRING, allowNull: true },
  estadoCivil: { type: DataTypes.STRING, allowNull: true },
  nacionalidade: { type: DataTypes.STRING, allowNull: true, defaultValue: "Brasileira" },
  naturalidade: { type: DataTypes.STRING, allowNull: true },
  nomeMae: { type: DataTypes.STRING, allowNull: true },
  nomePai: { type: DataTypes.STRING, allowNull: true },
  escolaridade: { type: DataTypes.STRING, allowNull: true },
  email: { type: DataTypes.STRING, allowNull: true },
  telefone: { type: DataTypes.STRING, allowNull: true },
  cep: { type: DataTypes.STRING, allowNull: true },
  endereco: { type: DataTypes.STRING, allowNull: true },
  numero: { type: DataTypes.STRING, allowNull: true },
  complemento: { type: DataTypes.STRING, allowNull: true },
  bairro: { type: DataTypes.STRING, allowNull: true },
  cidade: { type: DataTypes.STRING, allowNull: true },
  estado: { type: DataTypes.STRING, allowNull: true },
  ctpsNumero: { type: DataTypes.STRING, allowNull: true },
  ctpsSerie: { type: DataTypes.STRING, allowNull: true },
  ctpsUf: { type: DataTypes.STRING, allowNull: true },
  ctpsDigital: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true },
  pisPasepNit: { type: DataTypes.STRING, allowNull: true },
  tituloEleitor: { type: DataTypes.STRING, allowNull: true },
  zonaEleitoral: { type: DataTypes.STRING, allowNull: true },
  secaoEleitoral: { type: DataTypes.STRING, allowNull: true },
  certificadoReservista: { type: DataTypes.STRING, allowNull: true },
  cnh: { type: DataTypes.STRING, allowNull: true },
  cnhCategoria: { type: DataTypes.STRING, allowNull: true },
  cnhValidade: { type: DataTypes.DATEONLY, allowNull: true },
  dataAdmissao: { type: DataTypes.DATEONLY, allowNull: false },
  tipoContrato: { type: DataTypes.STRING, allowNull: false, defaultValue: "Prazo indeterminado" },
  dataFimContrato: { type: DataTypes.DATEONLY, allowNull: true },
  dataFimExperiencia: { type: DataTypes.DATEONLY, allowNull: true },
  cargo: { type: DataTypes.STRING, allowNull: false },
  cbo: { type: DataTypes.STRING, allowNull: true },
  departamento: { type: DataTypes.STRING, allowNull: true },
  localTrabalho: { type: DataTypes.STRING, allowNull: true },
  salarioBase: { type: DataTypes.DECIMAL(12, 2), allowNull: false, defaultValue: 0 },
  tipoSalario: { type: DataTypes.STRING, allowNull: false, defaultValue: "Mensal" },
  jornadaSemanal: { type: DataTypes.DECIMAL(6, 2), allowNull: true, defaultValue: 44 },
  horarioTrabalho: { type: DataTypes.STRING, allowNull: true },
  intervalo: { type: DataTypes.STRING, allowNull: true },
  sindicato: { type: DataTypes.STRING, allowNull: true },
  categoriaTrabalhador: { type: DataTypes.STRING, allowNull: true, defaultValue: "101 - Empregado geral" },
  eSocialMatricula: { type: DataTypes.STRING, allowNull: true },
  regimePrevidenciario: { type: DataTypes.STRING, allowNull: true, defaultValue: "RGPS" },
  optanteFgts: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: true },
  dataOpcaoFgts: { type: DataTypes.DATEONLY, allowNull: true },
  banco: { type: DataTypes.STRING, allowNull: true },
  agencia: { type: DataTypes.STRING, allowNull: true },
  conta: { type: DataTypes.STRING, allowNull: true },
  tipoConta: { type: DataTypes.STRING, allowNull: true },
  chavePix: { type: DataTypes.STRING, allowNull: true },
  formaPagamento: { type: DataTypes.STRING, allowNull: true, defaultValue: "Transferência bancária" },
  valeTransporte: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  valorValeTransporte: { type: DataTypes.DECIMAL(12, 2), allowNull: true },
  valeAlimentacao: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  valorValeAlimentacao: { type: DataTypes.DECIMAL(12, 2), allowNull: true },
  planoSaude: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  insalubridadePercentual: { type: DataTypes.DECIMAL(6, 2), allowNull: true },
  periculosidade: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: false },
  dependentes: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
  beneficios: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
  exameAdmissionalData: { type: DataTypes.DATEONLY, allowNull: true },
  exameAdmissionalValidade: { type: DataTypes.DATEONLY, allowNull: true },
  documentos: { type: DataTypes.JSON, allowNull: false, defaultValue: [] },
  dataDesligamento: { type: DataTypes.DATEONLY, allowNull: true },
  motivoDesligamento: { type: DataTypes.STRING, allowNull: true },
  status: { type: DataTypes.STRING, allowNull: false, defaultValue: "Ativo" },
  observacoes: { type: DataTypes.TEXT, allowNull: true },
})

module.exports = Funcionario
